# Generated by Django 5.0.1 on 2024-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Faculty',
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='course',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ExcelSheet',
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
