# Generated by Django 5.0.1 on 2024-03-07 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_rename_room_faculty_alter_timetableslot_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='room',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='faculty1_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty1/'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='faculty2_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty2/'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='faculty3_file',
            field=models.FileField(blank=True, null=True, upload_to='faculty3/'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='other_field1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='other_field2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='timestamp_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
