# Generated by Django 5.0.1 on 2024-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_generatedtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='rules',
            field=models.ManyToManyField(blank=True, to='timetable_app.rule'),
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rules',
        ),
        migrations.AddField(
            model_name='venue',
            name='rules',
            field=models.ManyToManyField(blank=True, to='timetable_app.rule'),
        ),
    ]
