# Generated by Django 5.0.1 on 2024-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_remove_timetableslot_course_remove_timetableslot_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
